<?php

/**
 * @file
 * Determination of user's Country based on IP.
 *
 * This module uses the IP Address that a user is connected from to deduce
 * the Country where the user is located. This method is not foolproof,
 * because a user may connect through an anonymizing proxy, or may be in
 * an unusual case, such as getting service from a neighboring country,
 * or using an IP block leased from a company in another country.
 * Additionally, users accessing a server on a local network may be using
 * an IP that is not assigned to any country (e.g. 192.168.x.x).
 *
 * Country determination occurs upon user login. If a country can be
 * determined from the IP address, the ISO 3166 2-character country code
 * is stored in the Backdrop $user object as $user->country_iso_code_2.
 * If no country can be determined, this member is left unset.
 *
 * The database used is maintained by ARIN, the American Registry for
 * Internet Numbers (http://www.arin.net/about_us/index.html), which is
 * one of the 5 official Regional Internet Registries (RIR) responsible
 * for assigning IP addresses. The claim is the database is 98% accurate,
 * with most of the problems coming from users in less-developed countries.
 * Regardless, there's no more-authoritative source of this information.
 *
 * @author Tim Rohaly.    <http://drupal.org/user/202830>
 */


/******************************************************************************
 * Backdrop Hooks                                                               *
 ******************************************************************************/

/**
 * Implements hook_permission().
 */
function ip2country_permission() {
  return array(
    'administer ip2country' => array(
      'title'       => t('Administer IP lookup settings'),
      'description' => t('Configure IP database and module test settings.'),
    ),
  );
}


/**
 * Implements hook_cron().
 *
 * Updates the IP to Country database automatically on a periodic
 * basis. Default period is 1 week.
 */
function ip2country_cron() {
  $config = config('ip2country.settings');

  // Utility functions for fetching and loading IP/Country DB from RIR.
  module_load_include('inc', 'ip2country');

  // Automatic database updates are disabled when $update_interval == 0.
  $update_interval = $config->get('update_interval');
  if ($update_interval && $config->get('last_update') <=
      REQUEST_TIME - $update_interval) {
    $status = ip2country_update_database($config->get('rir'));
    // Log to watchdog if requested.
    if ($config->get('watchdog')) {
      if ($status != FALSE) {  // Success.
        watchdog('ip2country', 'Database updated from @registry server. Table contains @rows rows.', array('@registry' => backdrop_strtoupper($config->get('rir')), '@rows' => $status), WATCHDOG_NOTICE);
      }
      else {  // Failure.
        watchdog('ip2country', 'Database update from @registry server FAILED.', array('@registry' => backdrop_strtoupper($config->get('rir'))), WATCHDOG_WARNING);
      }
    }
  }
}


/**
 * Implements hook_menu().
 */
function ip2country_menu() {
  $items = array();

  $items['admin/config/people/ip2country'] = array(
    'title'            => 'User location',
    'description'      => 'Settings for determining user location from IP address.',
    'access arguments' => array('administer ip2country'),
    'page callback'    => 'backdrop_get_form',
    'page arguments'   => array('ip2country_admin_settings'),
    'type'             => MENU_NORMAL_ITEM,
    'file'             => 'ip2country.admin.inc',
  );
  $items['admin/config/people/ip2country/update'] = array(
    'title'            => 'Update database',
    'access arguments' => array('administer ip2country'),
    'page callback'    => '_ip2country_update',
    'type'             => MENU_CALLBACK,
    'file'             => 'ip2country.admin.inc',
  );
  $items['admin/config/people/ip2country/lookup'] = array(
    'title'            => 'Lookup IP address in database',
    'access arguments' => array('administer ip2country'),
    'page callback'    => '_ip2country_lookup',
    'type'             => MENU_CALLBACK,
    'file'             => 'ip2country.admin.inc',
  );

  return $items;
}


/**
 * Implements hook_user_login().
 *
 * Detects IP and determines country upon user login.
 */
function ip2country_user_login(&$edit, &$account) {
  $config = config('ip2country.settings');

  // Successful login. First determine user's country based on IP.
  $ip = ip_address();
  $country_code = ip2country_get_country($ip);

  // Now check to see if this user has "administer ip2country" permission
  // and if debug mode set. If both are TRUE, use debug information
  // instead of real information.
  if (user_access('administer ip2country') &&
      $config->get('debug')) {
    $type = $config->get('test_type');
    if ($type == 0) {  // Debug Country entered.
      $country_code = $config->get('test_country');
    }
    else {  // Debug IP entered.
      $ip = $config->get('test_ip_address');
      $country_code = ip2country_get_country($ip);
    }
    backdrop_set_message(t('Using DEBUG value for Country - @country', array('@country' => $country_code)));
  }

  // Finally, save country, if it has been determined.
  if ($country_code) {
    // Store the ISO country code in the $user object.
    $account->country_iso_code_2 = $country_code;
    user_save($account);
  }
}


/**
 * Implements hook_user_presave().
 *
 * Takes care of storing country data into {users}.data.
 */
function ip2country_user_presave($account) {
  if (isset($account->country_iso_code_2)) {
    $account->data['country_iso_code_2'] = $account->country_iso_code_2;
  }
}


/**
 * Implements hook_user_load().
 *
 * Takes care of restoring country data from {users}.data.
 */
function ip2country_user_load($users) {
  foreach ($users as $user) {
    if (isset($user->data['country_iso_code_2'])) {
      $users[$user->uid]->country_iso_code_2 = $user->data['country_iso_code_2'];
    }
  }
}


/******************************************************************************
 * Module Functions                                                           *
 ******************************************************************************/


/**
 * Gets the ISO 3166 2-character country code from the IP address.
 *
 * @param
 *   IP address.
 *
 * @param $ip_address
 *   IP address either as a dotted quad string (e.g. "127.0.0.1") or
 *   as a 32-bit unsigned long integer.
 *
 * @return
 *   ISO 3166-1 2-character country code for this IP address, or
 *   FALSE if the lookup failed to find a country.
 */
function ip2country_get_country($ip_address) {
  $ipl = ip2long($ip_address);
  if (is_long($ip_address)) {
    $ipl = $ip_address;
  }

  // Locate IP within range.
  $sql    = "SELECT country FROM {ip2country}
             WHERE (:start >= ip_range_first AND :end <= ip_range_last) LIMIT 1";
  $result = db_query($sql, array(':start' => $ipl, ':end' => $ipl))->fetchField();

  return $result;
}


/**
 * Gets the total count of IP ranges in database.
 */
function ip2country_get_count() {
  $sql   = "SELECT COUNT(*) FROM {ip2country}";
  $count = db_query($sql)->fetchField();
  return (int) $count;
}
